### ISSUE TITLE
Server error when calling get_cutout()

### ISSUE THREAD

**Issue by GeorgKohl** [idies/pyJHTDB#30]
I'm using `get_cutout()` in the following way:
```python
lJHTDB = libJHTDB()
lJHTDB.initialize()
lJHTDB.add_token("my auth token")
...
result = lJHTDB.getCutout(data_set=dataset, field='u', time_step=time, start=start, end=end, step=step).astype(np.float32)
``` 
where `time`, `start`, `end`, and `step` are simple numpy arrays of type int32 with indices, and `dataset` is a string of the corresponding dataset. This is run inside some for loops for different indices and datasets.

Occasionally, I get the following server error:
```
0: SOAP 1.2 fault: SOAP-ENV:Receiver [no subcode]
"System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at TurbulenceService.Database.GetRawResults(IAsyncResult[] asyncRes, Byte[] result, Int32 components, Int32 X, Int32 Y, Int32 Z, Int32 T, Int32 Xwidth, Int32 Ywidth, Int32 Zwidth, Int32 Twidth, Int32[] serverX, Int32[] serverY, Int32[] serverZ, Int32[] serverT, Int32[] serverXwidth, Int32[] serverYwidth, Int32[] serverZwidth, Int32[] serverTwidth) in C:\Users\mwang93\Source\Repos\idies\Turbulence\Turbulence\TurbulenceWebServiceLibrary\Database.cs:line 2191
   at TurbulenceService.Database.GetRawData(DataSets dataset_enum, TableNames tableName, Int32 timestep, Int32 components, Int32 X, Int32 Y, Int32 Z, Int32 Xwidth, Int32 Ywidth, Int32 Zwidth) in C:\Users\mwang93\Source\Repos\idies\Turbulence\Turbulence\TurbulenceWebServiceLibrary\Database.cs:line 3776
   at TurbulenceService.Database.GetCutoutData(DataSets dataset_enum, TableNames tableName, Int32 tlow, Int32 components, Int32 xlow, Int32 ylow, Int32 zlow, Int32 Xwidth, Int32 Ywidth, Int32 Zwidth, Int32 x_stride, Int32 y_stride, Int32 z_stride, Int32 filter_width) in C:\Users\mwang93\Source\Repos\idies\Turbulence\Turbulence\TurbulenceWebServiceLibrary\Database.cs:line 3880
   at TurbulenceService.TurbulenceService.GetAnyCutoutWeb(String authToken, String dataset, String field, Int32 T, Int32 x_start, Int32 y_start, Int32 z_start, Int32 x_end, Int32 y_end, Int32 z_end, Int32 x_step, Int32 y_step, Int32 z_step, Int32 filter_width, String addr) in C:\Users\mwang93\Source\Repos\idies\Turbulence\Turbulence\WebSite\App_Code\WebService.cs:line 4918
   --- End of inner exception stack trace ---"
Detail: [no detail]
```

Unfortunately, I can't find a way to reliably reproduce it, it simple happens from time to time. Any idea what might the problem here?

**Comment by GeorgKohl** [comment]
I think it might be related to issue #29, as the error looks similar
